---

- name: Install required packages
  apt:
    name: {{ item }}
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ shorewall__base_packages  }}'
    - '{{ shorewall__packages  }}'
  register: shorewall__register_install

- name: Configuring Shorewall defaults
  template:
    src: "etc/default/shorewall.j2"
    dest: "/etc/default/shorewall"
    owner: "root"
    group: "root"
    mode: 0640
  notify:
    - 'restart shorewall'

- name: Configuring Shorewall main configuration
  template:
    src: "etc/shorewall/shorewall.conf.j2"
    dest: "/etc/shorewall/shorewall.conf"
    owner: "root"
    group: "root"
    mode: 0640
  notify:
    - 'restart shorewall'

- name: Configuring Shorewall interfaces
  template:
    src: "etc/shorewall/interfaces.j2"
    dest: "/etc/shorewall/interfaces"
    owner: "root"
    group: "root"
    mode: 0640
  notify:
    - 'restart shorewall'

- name: Configuring Shorewall zones
  template:
    src: "etc/shorewall/zones.j2"
    dest: "/etc/shorewall/zones"
    owner: "root"
    group: "root"
    mode: 0640
  notify:
    - 'restart shorewall'

- name: Configuring Shorewall policies
  template:
    src: "etc/shorewall/policy.j2"
    dest: "/etc/shorewall/policy"
    owner: "root"
    group: "root"
    mode: 0640
  notify:
    - 'restart shorewall'

- name: Configuring Shorewall rules
  template:
    src: "etc/shorewall/rules.j2"
    dest: "/etc/shorewall/rules"
    owner: "root"
    group: "root"
    mode: 0640
  notify:
    - 'restart shorewall'

- name: Configuring Shorewall masquerading
  template:
    src: "etc/shorewall/masq.j2"
    dest: "/etc/shorewall/masq"
    owner: "root"
    group: "root"
    mode: 0640
  notify:
    - 'restart shorewall'

- name: Configuring Shorewall nat
  template:
    src: "etc/shorewall/nat.j2"
    dest: "/etc/shorewall/nat"
    owner: "root"
    group: "root"
    mode: 0640
  notify:
    - 'restart shorewall'
